global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # retention: 48h

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

rule_files:
  - 'alertrule.yml'  # Ensure this file exists and is correctly named

scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
    - targets: ['node_exporter:9100']
      labels:
          instance: test_Server
    
  - job_name: 'ALPHA-EQUIPO'
    scrape_interval: 5s
    static_configs:
    - targets: ['35.89.17.180:9100']
      labels:
          instance: ALPHA-ADMIN-PANEL-API

  - job_name: 'alertmanager'
    static_configs:
    - targets: ['alertmanager:9093']
