apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-wal-pv
  namespace: monitoring
  labels:
    app: loki-wal-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/loki-wal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-wal-pvc
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 5Gi  # Define the desired storage capacity
  accessModes:
    - ReadWriteOnce