apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |
    logging {
      level  = "info"
      format = "logfmt"
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    discovery.kubernetes "nodes" {
      role = "node"
    }

    prometheus.scrape "default" {
      targets = discovery.kubernetes.pods.targets
      forward_to = [otelcol.processor.batch.default.input]
    }

    otelcol.processor.batch "default" {
      send_batch_size = 2000
      send_batch_max_size = 3000
      timeout = "10s"
      
      output {
        metrics = [prometheus.remote_write.mimir.receiver]
        logs    = [loki.write.loki.receiver]
        traces  = [otelcol.exporter.otlp.tempo.input]
      }
    }

    prometheus.remote_write "mimir" {
      endpoint {
        url = "http://mimir-service.monitoring.svc.cluster.local:8080/api/v1/push"
        basic_auth {
          username = env("MIMIR_USERNAME")
          password = env("MIMIR_PASSWORD")
        }
      }
    }

    loki.source.kubernetes "pods" {
      targets = discovery.kubernetes.pods.targets
      forward_to = [otelcol.processor.batch.default.input]
    }

    loki.write "loki" {
      endpoint {
        url = "http://loki-service.monitoring.svc.cluster.local:3100/loki/api/v1/push"
        basic_auth {
          username = env("LOKI_USERNAME")
          password = env("LOKI_PASSWORD")
        }
      }
    }

    otelcol.receiver.otlp "default" {
      grpc {
        endpoint = "0.0.0.0:4317"
      }
      http {
        endpoint = "0.0.0.0:4318"
      }

      output {
        traces = [otelcol.processor.batch.default.input]
      }
    }

    otelcol.exporter.otlp "tempo" {
      client {
        endpoint = "http://tempo-service.monitoring.svc.cluster.local:4317"
        tls {
          insecure = true
        }
        auth {
          basic {
            username = env("TEMPO_USERNAME")
            password = env("TEMPO_PASSWORD")
          }
        }
      }
    }
