apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
    common:
      path_prefix: /data/loki
      replication_factor: 1
      ring:
        instance_addr: 0.0.0.0
        kvstore:
          store: memberlist
    storage_config:
      aws:
        s3: s3://us-west-2/ebs-monitoring-data/data/loki
        region: us-west-2
        s3forcepathstyle: true
      tsdb_shipper:
        active_index_directory: /data/loki/tsdb-shipper-active
        cache_location: /data/loki/tsdb-shipper-cache
    schema_config:
      configs:
        - from: 2025-01-01
          store: tsdb
          object_store: aws
          schema: v13
          index:
            prefix: index_
            period: 24h
    compactor:
      working_directory: /data/loki/compactor
      retention_enabled: true
      retention_delete_delay: 2h
      delete_request_store: aws
      compactor_ring:
        kvstore:
          store: memberlist
    limits_config:
      retention_period: 2160h
      max_query_lookback: 2160h
      max_query_length: 2160h
      query_timeout: 30m
      max_entries_limit_per_query: 5000
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    ingester:
      wal:
        enabled: true
        dir: /data/loki/wal
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 1h
      max_chunk_age: 1h
      chunk_target_size: 1536000
      chunk_retain_period: 30s
    querier:
      query_ingesters_within: 3h
      max_concurrent: 8
    frontend:
      log_queries_longer_than: 5s
      split_queries_by_interval: 24h
    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 2048
      parallelise_shardable_queries: true
    ruler_storage:
      backend: local
      local:
        directory: /data/loki/rules
    ruler:
      rule_path: /data/loki/rules-temp
      ring:
        kvstore:
          store: memberlist
      enable_api: true
