apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki.yaml: |
    server:
      http_listen_port: 3100
      http_path_prefix: /loki
      log_level: info
    auth_enabled: false
    target: all
    schema_config:
      configs:
        - from: 2025-01-01
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage_config:
      aws:
        s3: s3://us-west-2/ebs-monitoring-data/loki
        region: us-west-2
      tsdb_shipper:
        active_index_directory: /tmp/loki/index
        cache_location: /tmp/loki/cache
    compactor:
      working_directory: /tmp/loki/compactor
      shared_store: s3
      retention_enabled: true
      retention_delete_delay: 2h
    limits_config:
      ingestion_rate_mb: 4
      ingestion_burst_size_mb: 8
      max_query_lookback: 168h
      max_cache_freshness_per_query: 10m
    chunk_store_config:
      max_look_back_period: 168h
    query_range:
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            size: 1024
            validity: 24h
