auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  # http_path_prefix: /logs
  log_level: info
  graceful_shutdown_timeout: 30s

memberlist:
  join_members:
    - loki
  bind_port: 7946
  max_join_backoff: 1m
  max_join_retries: 10
  abort_if_cluster_join_fails: false

common:
  path_prefix: /data/loki
  replication_factor: 1
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: memberlist

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki/index_
        period: 24h

storage_config:
  aws:
    region: us-west-2
    bucketnames: ebs-monitoring-data
    s3forcepathstyle: false
    insecure: false
  tsdb_shipper:
    active_index_directory: /data/loki/tsdb-index
    cache_location: /data/loki/tsdb-cache

compactor:
  working_directory: /data/loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  delete_request_store: s3
  retention_delete_worker_count: 150

limits_config:
  retention_period: 2160h
  max_query_lookback: 2160h
  ingestion_rate_mb: 64
  ingestion_burst_size_mb: 128
  max_streams_per_user: 100000
  max_global_streams_per_user: 100000

ingester:
  wal:
    enabled: true
    dir: /data/loki/wal
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1536000
  chunk_retain_period: 30s
  flush_check_period: 30s

querier:
  query_ingesters_within: 3h

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
