auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info
  graceful_shutdown_timeout: 30s
  # http_path_prefix: /loki

memberlist:
  join_members:
    - loki
  bind_port: 7946
  max_join_backoff: 1m
  max_join_retries: 10
  abort_if_cluster_join_fails: false

common:
  path_prefix: /data/loki
  replication_factor: 1
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: memberlist

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki/index_
        period: 24h

storage_config:
  aws:
    region: ${AWS_REGION}
    bucketnames: ${S3_BUCKET_NAME}
    endpoint: s3.${AWS_REGION}.amazonaws.com
    s3forcepathstyle: false
    insecure: false
  tsdb_shipper:
    active_index_directory: /data/loki/tsdb-index
    cache_location: /data/loki/tsdb-cache
    shared_store: s3

compactor:
  working_directory: /data/loki/compactor
  shared_store: s3
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  delete_request_store: s3
  retention_delete_worker_count: 150

limits_config:
  retention_period: 2160h # 90 days
  max_query_lookback: 2160h
  max_query_length: 2160h
  query_timeout: 30m
  max_entries_limit_per_query: 5000
  reject_old_samples: true
  reject_old_samples_max_age: 168h # 7 days
  split_queries_by_interval: 24h
  ingestion_burst_size_mb: 128
  ingestion_rate_mb: 64
  max_streams_per_user: 100000
  max_global_streams_per_user: 100000

ingester:
  wal:
    enabled: true
    dir: /data/loki/wal
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1536000
  chunk_retain_period: 30s
  flush_check_period: 30s

querier:
  query_ingesters_within: 3h
  max_concurrent: 8

frontend:
  log_queries_longer_than: 5s
  compress_responses: true

frontend_worker:
  frontend_address: 127.0.0.1:9095
