apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-wal-pv
  labels:
    app: loki-wal-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/loki-wal