name: Security Scan

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:
  security:
    runs-on: [self-hosted, sonar-qube]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -------------------------
      # Trivy Vulnerability Scan
      # -------------------------
      - name: Trivy FS Scan (SARIF)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: sarif
          output: trivy-results.sarif
          scanners: vuln,secret,config
          severity: CRITICAL,HIGH

      # -------------------------
      # SonarQube Code Scan
      # -------------------------
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: http://nginx
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ github.repository }}
            -Dsonar.sources=.
            -Dsonar.sarifReportPaths=trivy-results.sarif

      # -------------------------
      # Quality Gate Enforcement
      # -------------------------
      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
