apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: default
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      ring:
        kvstore:
          store: memberlist
        replication_factor: 1
      path_prefix: /loki

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s

    memberlist:
      join_members:
        - loki-service.default.svc.cluster.local:7946

    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
      aws:
        bucketnames: ebs-monitoring-logs
        endpoint: s3.us-west-2.amazonaws.com
        region: us-west-2
        access_key_id: DOntDOThisForProd
        secret_access_key: DOntDOThisForProd
        insecure: false
        s3forcepathstyle: true
        http_config:
          idle_conn_timeout: 90s
          response_header_timeout: 0s
          insecure_skip_verify: false

    schema_config:
      configs:
        - from: 2020-07-01
          store: tsdb
          object_store: aws
          schema: v13
          index:
            prefix: index_
            period: 24h

    compactor:
      working_directory: /tmp/loki/compactor
      retention_enabled: true
      delete_request_store: s3


    chunk_store_config: {}

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_entries_limit_per_query: 5000
      max_streams_per_user: 0
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      max_query_series: 100000
      max_label_names_per_series: 100
      max_label_name_length: 1024
      max_label_value_length: 2048
      max_query_length: 1h
      max_query_parallelism: 32

    frontend:
      compress_responses: true
      log_queries_longer_than: 5s
      max_outstanding_per_tenant: 2048

    query_range:
      align_queries_with_step: true
      max_retries: 5
      parallelise_shardable_queries: true

    ruler:
      storage:
        type: local
        local:
          directory: /tmp/loki/rules
      rule_path: /tmp/loki/rules-temp
      alertmanager_url: http://alertmanager-service.default.svc.cluster.local:9093
      ring:
        kvstore:
          store: memberlist
      enable_api: true

    table_manager:
      retention_deletes_enabled: true
      retention_period: 90d


