apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: default
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      ring:
        kvstore:
          store: memberlist
        replication_factor: 1
      path_prefix: /loki

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
        final_sleep: 0s

    memberlist:
      join_members:
        - loki-service.default.svc.cluster.local:7946

    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
      aws:
        bucketnames: test-monitoring-logs
        endpoint: s3.us-west-2.amazonaws.com
        region: us-west-2
        access_key_id: key
        secret_access_key: key
        insecure: false
        http_config:
          idle_conn_timeout: 90s
          response_header_timeout: 0s
          insecure_skip_verify: false
        s3forcepathstyle: true

    schema_config:
      configs:
        - from: 2020-07-01
          store: tsdb
          object_store: aws
          schema: v13
          index:
            prefix: index_
            period: 24h

    compactor:
      working_directory: /tmp/loki/compactor

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    chunk_store_config: {}

    table_manager:
      retention_deletes_enabled: true
      retention_period: 90d