# loki-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  namespace: monitoring
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
        - name: setup-permissions
          image: busybox
          command: ["sh", "-c", "chmod 777 -R /tmp/wal"]
          volumeMounts:
            - name: wal-volume
              mountPath: /tmp/wal
      containers:
        - name: loki
          image: grafana/loki:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3100
              name: http
            - containerPort: 9096
              name: grpc
          args:
            - "-config.file=/etc/loki/loki.yaml"
            - "-config.expand-env=true"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/loki/loki.yaml
              subPath: loki.yaml
            - name: wal-volume
              mountPath: /tmp/wal
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: config-volume
          configMap:
            name: loki-config
        - name: wal-volume
          persistentVolumeClaim:
            claimName: loki-wal-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: monitoring
  labels:
    app: loki
spec:
  type: NodePort
  ports:
    - name: lokihttp
      protocol: TCP
      targetPort: http
      port: 3100
      nodePort: 31000
    - name: lokigrpc
      protocol: TCP
      targetPort: grpc
      port: 9096
      nodePort: 32000
  selector:
    app: loki

