apiVersion: v1
kind: Secret
metadata:
  name: loki-secrets
  namespace: monitoring
type: Opaque
data:
  AWS_ACCESS_KEY_ID: eW91ci1hd3MtYWNjZXNzLWtleQ==   # Base64 encoded value
  AWS_SECRET_ACCESS_KEY: eW91ci1hd3Mtc2VjcmV0LWtleQ==  # Base64 encoded value
  LOKI_USERNAME: eW91ci1sb2tpLXVzZXJuYW1l  # Base64 encoded value
  LOKI_PASSWORD: eW91ci1sb2tpLXBhc3N3b3Jk  # Base64 encoded value
