apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: haproxy
    haproxy.org/ssl-redirect: "false"
    haproxy.org/path-rewrite: |
      /loki/(.*) /\1
      /tempo/(.*) /\1
spec:
  ingressClassName: haproxy
  rules:
    - http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  name: grafana

          - path: /loki(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: loki-service
                port:
                  name: loki

          - path: /tempo(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tempo-service
                port:
                  name: tempo

          - path: /mimir
            pathType: Prefix
            backend:
              service:
                name: mimir-service
                port:
                  name: mimir
